# Generated by Django 4.2 on 2023-04-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_additem_company_details_history_purchase_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxitem',
            name='interstate',
            field=models.CharField(choices=[('IGST0[0%]', 'IGST0[0%]'), ('IGST5[5%]', 'IGST5[5%]'), ('IGST12[12%]', 'IGST12[12%]'), ('IGST18[18%]', 'IGST18[18%]'), ('IGST28[28%]', 'IGST28[28%]')], default='IGST0[0%]', max_length=255),
        ),
        migrations.AlterField(
            model_name='taxitem',
            name='intrastate',
            field=models.CharField(choices=[('GST0[0%]', 'GST0[0%]'), ('GST5[5%]', 'GST5[5%]'), ('GST12[12%]', 'GST12[12%]'), ('GST18[18%]', 'GST18[18%]'), ('GST28[28%]', 'GST28[28%]')], default='GST0[0%]', max_length=255),
        ),
    ]
