# Generated by Django 4.2 on 2023-04-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0003_alter_taxitem_interstate_alter_taxitem_intrastate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='tax',
        ),
        migrations.AddField(
            model_name='additem',
            name='interstate',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additem',
            name='intrastate',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TaxItem',
        ),
    ]
