# Generated by Django 4.1.7 on 2023-04-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0004_remove_additem_tax_additem_interstate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetainerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('retainer_invoice_number', models.CharField(max_length=255)),
                ('refrences', models.CharField(max_length=255)),
                ('retainer_invoice_date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_notes', models.TextField()),
                ('is_draft', models.BooleanField(default=True)),
                ('is_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
