# Generated by Django 4.1.7 on 2023-04-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0006_customer_alter_retainerinvoice_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='retainerinvoice',
            name='terms_and_conditions',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
