# Generated by Django 4.1.7 on 2023-04-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0008_alter_retainerinvoice_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retainerinvoice',
            name='amount',
            field=models.CharField(max_length=100),
        ),
    ]
