# Generated by Django 4.1.7 on 2023-05-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0009_alter_retainerinvoice_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retainerinvoice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='retainerinvoice',
            name='description',
        ),
    ]
