# Generated by Django 4.0.2 on 2023-05-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0012_vendor_table_mail_table_doc_upload_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='interstate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='additem',
            name='intrastate',
            field=models.CharField(default='', max_length=255),
        ),
    ]
